# Model configuration
model:
  hidden_size: 768
  cross_attention_dim: 2048
  sigma_data: 1.0
  sigma_min: 0.002
  sigma_max: 20000.0
  rho: 7.0
  num_timesteps: 1000
  min_snr_gamma: 0.1
  pretrained_model_name: "stabilityai/stable-diffusion-xl-base-1.0"

# Training configuration
training:
  batch_size: 32
  gradient_accumulation_steps: 4
  learning_rate: 4.0e-7
  num_epochs: 10
  save_steps: 1000
  log_steps: 10
  mixed_precision: "bf16"
  weight_decay: 1.0e-2
  optimizer_eps: 1.0e-8
  optimizer_betas: [0.9, 0.999]

# Data configuration
data:
  image_size: [1024, 1024]  # Base area for scaling
  num_workers: 8
  pin_memory: true
  persistent_workers: true
  shuffle: true
  image_dirs: [
    "/path/to/dataset1",
    "/path/to/dataset2",
    "/path/to/dataset3"
  ]
  cache_dir: "latent_cache"
  text_cache_dir: "text_cache"

# Tag weighting configuration
tag_weighting:
  min_weight: 0.1
  max_weight: 2.0
  default_weight: 1.0
  enabled: true  # Whether to use tag weighting
  update_frequency: 1000  # How often to recompute weights (in steps)
  smoothing_factor: 0.1  # For exponential moving average of weights

# Scoring configuration
scoring:
  aesthetic_score: 6.0
  crop_score: 3.0

# System configuration
system:
  enable_xformers: true
  channels_last: true
  gradient_checkpointing: true
  cudnn_benchmark: true
  disable_debug_apis: true

# Paths configuration
paths:
  checkpoints_dir: "checkpoints"
  logs_dir: "logs"
  output_dir: "outputs"