# Model configuration
model:
  sigma_data: 1.0
  sigma_min: 0.002
  sigma_max: 20000.0
  rho: 7.0
  num_timesteps: 1000
  min_snr_gamma: 0.1
  pretrained_model_name: "stabilityai/stable-diffusion-xl-base-1.0"

# Training configuration
training:
  batch_size: 32
  gradient_accumulation_steps: 4
  learning_rate: 4.0e-7
  vae_learning_rate: 4.5e-5
  vae_warmup_steps: 1000
  vae_min_lr: 1e-6
  use_discriminator: true
  discriminator_learning_rate: 4.5e-5
  num_epochs: 10
  save_steps: 1000
  log_steps: 10
  mixed_precision: "bf16"
  weight_decay: 1.0e-2
  optimizer_eps: 1.0e-8
  optimizer_betas: [0.9, 0.999]
  prediction_type: "v_prediction"
  timestep_bias_strategy: "none"
  timestep_bias_multiplier: 1.0
  timestep_bias_begin: 0
  timestep_bias_end: 1000
  timestep_bias_portion: 0.25
  snr_gamma: 5.0
  max_grad_norm: 1.0
  early_stopping_patience: 5
  early_stopping_threshold: 0.01
  

# Data configuration
data:
  # List of directories containing training images
  # Example:
  # image_dirs: 
  #   - "/path/to/dataset1"
  #   - "/path/to/dataset2"
  image_dirs: [
        "/workspace/collage",
        "/workspace/upscaled",
        "/workspace/High-quality-photo10k",
        "/workspace/LAION_220k_GPT4Vision_captions",
        "/workspace/photo-concept-bucket/train"
    ]
  image_size: [1024, 1024]
  num_workers: 8
  pin_memory: true
  persistent_workers: true
  shuffle: true
  cache_dir: "latent_cache"
  text_cache_dir: "text_cache"
  vae_batch_size: 32
  vae_image_size: [256, 256]
  vae_validation_split: 0.1

# Tag weighting configuration
tag_weighting:
  enabled: true
  min_weight: 0.1
  max_weight: 2.0
  default_weight: 1.0
  update_frequency: 1000
  smoothing_factor: 0.1

# Scoring configuration
scoring:
  aesthetic_score: 6.0
  crop_score: 3.0

# System configuration
system:
  enable_xformers: true
  channels_last: true
  gradient_checkpointing: true
  cudnn_benchmark: true
  disable_debug_apis: true
  compile_model: true
  num_gpu_workers: null
  distributed_training: true
  backend: "nccl"
  use_fsdp: true
  cpu_offload: false
  full_shard: true
  mixed_precision: "bf16"
  gradient_accumulation_steps: 4
  sync_batch_norm: true
  min_num_params_per_shard: 1000000  # 1M parameters per shard
  forward_prefetch: true
  backward_prefetch: true
  limit_all_gathers: true
  find_unused_parameters: false

# Paths configuration
paths:
  checkpoints_dir: "checkpoints"
  logs_dir: "logs"
  output_dir: "outputs"
  vae_checkpoints_dir: "vae_checkpoints"
  vae_samples_dir: "vae_samples"